### ISSUE TITLE
Handle errors on logout request

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/console#1026]
I'm not sure if this is specific to IdP users or something else.  I'm able to log out successfully when I logged in with spoof_login as privileged user.  But when I logged in with SAML and then click "Sign out", I get no visual feedback at all (nothing happens).  There's a 403 error in the console.

Nexus reported:

```
Jun 30 21:28:41.134 INFO request completed, error_message_external: Forbidden, error_message_internal: Forbidden, response_code: 403, uri: /logout, method: POST, req_id: 05d47fe1-01ca-4ea3-a749-3f65e563245a, remote_addr: 127.0.0.1:45179, local_addr: 127.0.0.1:12220, component: dropshot_external, name: e6bff1ff-24fb-49dc-a54e-c6a350cd4d6c
```

That might be an Omicron bug but I imagine the console should do something different here?

**Comment by david-crespo** [comment]
Can't repro anymore. Logout with SAML IDP seems to work fine, even tried it after deleting session cookie to make sure logout with invalid auth is a "successful" noop and results in redirect to login page.
