### ISSUE TITLE
Add tooltips for disabled menu items and buttons

### ISSUE THREAD

**Issue by zephraph** [oxidecomputer/console#1029]
There are cases when we disable items in menus when the action is invalid in the current context. For example, you can't change a disk if it's attached to a running instance. We try to give context in the view that hopefully hints to why something is grayed out, but more explicit feedback would be helpful.

There's a strong argument that this would be an accessibility win too. As a sighted user, it's easy to glance at the bottom of a page and see a message saying certain things are disabled because of the state of the instance or something. Unless we use an announce or somehow add that messaging at a higher level in the accessible flow (which we likely should still do), it's possible that a user could get to the action before actually having the reason for its disabled state being announced. Having this extra context would mean that the button/item is announced as disabled along with context of why its disabled.

**Comment by david-crespo** [comment]
We're using this in a few places. If we want it in particular places we can make issues or just do it.
