### ISSUE TITLE
Combine `MoreActionsMenu` and `getActionsCol`

### ISSUE THREAD

**Issue by zephraph** [oxidecomputer/console#1054]
Currently `MoreActionsMenu` and `getActionsCol` have some weird overlap. We should likely consolidate around the `MoreActionsMenu`, allow the `MenuButton` to be passed as a child and tidy up `getActionsCol`. 

Fixing this would make it easier to share global actions like with #1053. Beyond that though, they could just use some love.

**Comment by david-crespo** [comment]
Confirmed that this is still the case. `MoreActionsMenu` and `getActionsCol` do almost exactly the same thing — translate a list of action objects into a dropdown menu. We should refactor these to at least share their core, if not fully combine them.

https://github.com/oxidecomputer/console/blob/046928022a7cb1fa7152819d6883155609ad4726/app/components/MoreActionsMenu.tsx#L20-L44

https://github.com/oxidecomputer/console/blob/046928022a7cb1fa7152819d6883155609ad4726/app/table/columns/action-col.tsx#L38-L91

**Comment by david-crespo** [comment]
Meh, this is fine. We can fix things up if we ever change either of these things.

**Comment by zephraph** [comment]
tru
