### ISSUE TITLE
Number input styling

### ISSUE THREAD

**Issue by paryhin** [oxidecomputer/console#1072]
![image](https://user-images.githubusercontent.com/56555905/181056714-6d52daa0-fe1a-43f7-9464-5201d2f65c17.png)

Hey, the styling of this element looks off, and the arrows make it look like a dropdown component.  We may want to use a regular input for now, or create a new component for this use case, something like:

<img width="538" alt="CleanShot 2022-07-26 at 19 47 03@2x" src="https://user-images.githubusercontent.com/56555905/181063919-96e1430e-d381-4f11-ab1a-15b5efff6024.png">

**Comment by david-crespo** [comment]
Done in #1582
