### ISSUE TITLE
Ephemeral IP checkbox on instance create form

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/console#1097]
Beginning with https://github.com/oxidecomputer/omicron/pull/1458, the control plane now has the concept of an external IP address for guests. This is a publicly-visible address that allows inbound connections, such as SSH, from outside the rack into the guest. (That's distinct from the IP addresses that provide outbound connectivity, which don't appear in the API.)

These addresses are associated with the primary network interface, and are shown in the console as part of https://github.com/oxidecomputer/console/pull/1070. We also need a way to request such an address in the web console. The parameters for describing this address are currently defined [here](https://github.com/oxidecomputer/omicron/blob/232806389f022cb5db0e9e4911aa6abb5fe90f00/nexus/types/src/external_api/params.rs#L409). We currently support ephemeral addresses, optionally specifying the name of an IP Pool from which to draw the address. (Ephemeral addresses only live as long as the instance, and can't move around between different objects.) It's not clear yet how to specify the pool, since that's currently a top-level / operator / global resource (discussed in RFD 288), so it might be better to leave that off for now.

Though they're not yet implemented, Floating IP addresses will also be supported here. (Implementation tracked in https://github.com/oxidecomputer/omicron/issues/1334.) Those are separate, named API resources scoped to a VPC, which can be created independently from instances. In that case, the name of the Floating IP will be specified in the API request (it'll be looked up relative to the VPC of the primary network interface, most likely).

**Comment by david-crespo** [comment]
This bit would be populated or empty based on the checkbox value.

https://github.com/oxidecomputer/console/blob/046928022a7cb1fa7152819d6883155609ad4726/app/forms/instance-create.tsx#L213

**Comment by paryhin** [comment]
Based on the discussions we had, here is the Figma file with relevant designs: 

https://www.figma.com/file/zIBsgP7gAkhapyNvVOqsn6/Floating-IPs?type=design&node-id=427%3A22653&mode=design&t=SaUnqJRcykwBNbPD-1
