### ISSUE TITLE
Specify IP pool for ephemeral IP on instance create

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#1098]
Split off from #1097

> It's not clear yet how to specify the pool, since that's currently a top-level / operator / global resource (discussed in RFD 288), so it might be better to leave that off for now.

**Comment by paryhin** [comment]
We can reuse the pattern that we have for other entities on instance create page.



![Image](https://github.com/oxidecomputer/console/assets/56555905/bcc148b4-befc-4175-9239-e0df8514ee3b)
