### ISSUE TITLE
MVP Image Flow

### ISSUE THREAD

**Issue by benjaminleonard** [oxidecomputer/console#1411]
##  MVP Image Flow
This is a proposal for a UX flow for handling project and silo images. Still to change based on the outcome of any discussion here and in [RFD 362](https://rfd.shared.oxide.computer/rfd/0362).

As an end-user looking at the images page within a project you see a list of images. The all tab aggregates all images that developers can use. The local tab contains all images that are not shared outside of the project. The silo tab shows images that have been promoted (both images that may have originally been created inside this project and ones from other projects).

![image](https://user-images.githubusercontent.com/4020798/225905219-94e8d529-05bb-425d-9627-109568b2729b.png)

Here we see the modal for adding a new image to a project. An image can only be added to a project and then later promoted to the silo, they cannot be added directly to a silo. The `Operating System` field is a combobox that allows the user to both select an existing family name and a freeform text input for names that aren't already in-use. This is to avoid the accidental creation of duplicate OS'. We might also want to use validation on a lowercased name, e.g. to avoid something like `Freebsd` and `FreeBSD`.

![image](https://user-images.githubusercontent.com/4020798/225906354-c181e1b3-cd09-4a01-ae1b-4216aac6138f.png)

If the user then decides to promote an image they can do so through the actions dropdown. Only a user with the `Silo Admin` role can do so. For users without this role we can disable the button in the dropdown and show a tooltip explaining why. We also provide a notice clarifying that "Promoted images can only be edited by a user with the Silo Admin role". 

![image](https://user-images.githubusercontent.com/4020798/225907537-286681dc-2f93-4619-9f8c-37645d665f58.png)

We check for name uniqueness at promote-time. If another image exists with the same name, the promotion fails and we include an 'Edit Image' CTA. This opens a modal to edit the image and attempt the promotion again.

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/4020798/225908015-13078c4c-e6a4-44fa-ad56-794469272c40.png">

The edit modal gives us the option to edit an images metadata. Do we also want to include the ability to edit an images source here?

![image](https://user-images.githubusercontent.com/4020798/225908479-b1c572d3-108b-435a-927e-d23d5f846d7f.png)

Here we see an alternate version of the edit modal but for an image that has been promoted. In this case the user does not have the `Silo Admin` and therefore cannot make changes to the image, even if it was originally promoted from within a project to which they have a `Project Admin` role.

![image](https://user-images.githubusercontent.com/4020798/225910604-f374df6f-5e08-4718-b0c5-53f744bdddc5.png)

The silo also has an images page which contains only the images that are shared across the silo. This page mostly mirrors the project one, but does not distinguish between image types. It does include the name of the project that the image originates from in the table.

![image](https://user-images.githubusercontent.com/4020798/225909160-b6402b68-6abd-4e8b-93a2-a0d10a6ac516.png)

##  Other considerations
- Some metrics on how recently and frequently an image has been used might be helpful to an operators that is looking to remove unused images
- We might want to be clearer on how the choice of image affects functionality, e.g. we cannot inject SSH keys automatically into an image without `cloud-init`
- Here I'm using `Project Image` and `Silo Image` as I think it better reflects the implementation. In my mind `Global Image` can be used across silos.
- Alternatively if we don't want to enforce name uniqueness on promoted images, we could use the project name to namespace images

**Comment by david-crespo** [comment]
We have demo and delete. Edit is kind of meh, we don't have an API endpoint for it, I think because it would be weird to change the names under people.
