### ISSUE TITLE
feedback on instance refresh button

### ISSUE THREAD

**Issue by citrus-it** [oxidecomputer/console#1552]
When clicking the refresh button at the top right of the instance list, there is no feedback. Is it possible to do something such as display the progress bar briefly?

<img width="362" alt="image" src="https://github.com/oxidecomputer/console/assets/29426693/d82c83f8-9299-4f9c-b017-39f499b49283">

It would also be useful to have a refresh button the instance page itself as I find myself refreshing the whole page via the browser when waiting for a large instance to start.

**Comment by charliepark** [comment]
These are both in place now — feedback on refresh, and refresh button on the instance view page (along with the auto-refresh functionality) — so I'm closing this one.
