### ISSUE TITLE
Firewall rule issues

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/console#1571]
There are several issues with the popup for adding/editing firewall rules:

1. Unable to add multiple host filters of the same host type when editing an existing firewall rule: I tried to add 2 different IP addresses under the host filter section but it only allows the first one. There is no javascript error as far as I can tell from the browser console. (Interestingly, I am able to do so if I add a new fw rule.)

2. Target name is always reset to "VPC name" after adding a target: This issue happens to both Target and Host filters. The name field is set dynamically set based on the target/host type, e.g. VPC name, Instance name, IP name. After adding an IP address, the name field is reset to "VPC name" while the type stays as "IP". If I enter a second IP address in the name box now, it's added as VPC.
<img width="509" alt="image" src="https://github.com/oxidecomputer/console/assets/10874909/85c88d3d-d539-4a10-b84c-7b316233a27a">
To workaround this, I have to toggle the "Type" dropdown to something else and then back to IP (to poke the onChange action). It's a minor annoyance.

**Comment by david-crespo** [comment]
I just used the form last night and boy is it awful!

**Comment by david-crespo** [comment]
1 is fixed in #1887
