### ISSUE TITLE
Long disk name on disk metrics is crammed in

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#1579]
Probably just needs an ellipsis.

<img width="250" alt="Screenshot 2023-06-10 at 2 59 19 PM" src="https://github.com/oxidecomputer/console/assets/3612203/979e73d3-02ef-480c-b90c-aa71f90a3ea4">

**Comment by augustuswm** [comment]
![de3bdd7e-9ace-4b1d-a34b-fd2933cce4bb](https://github.com/oxidecomputer/console/assets/1377730/4da7caa8-86ca-450c-8639-0aad9a5ca760)

**Comment by charliepark** [comment]
This is working now with an ellipsis, so I'll close it.

![Image](https://github.com/user-attachments/assets/678299ca-4daa-438e-b950-c5eccfbd3dee)
![Image](https://github.com/user-attachments/assets/9a71b45b-e7be-4b50-af0a-43a69ff08865)
