### ISSUE TITLE
Editing instance settings while it's being created

### ISSUE THREAD

**Issue by mkeeter** [oxidecomputer/console#1613]
It's possible to edit instance settings while it's in the process of being created.

If you do that, then when the instance is created, you get a "your changes won't be saved" popup, which is very confusing.

https://github.com/oxidecomputer/console/assets/745333/5697cfbf-72bc-4bea-ac23-accbd18689c8

**Comment by benjaminleonard** [comment]
A few options for fixing this:

1. Only block navigating away if the form is not submitting. This seems to work on the mock API:
`const blocker = useBlocker(isDirty && isSubmitting)`. Easy fix, users can still edit the field...maybe fine?

2. Disable key and pointer events on the form whilst it's submitting. Perhaps weird for the user not to be able to select their inputs whilst submitting?

3. Extend the controller component (https://react-hook-form.com/advanced-usage#TransformandParse) subscribe to formState.isSubmitting and disable the inputs when a form is submitting. Perhaps the most robust and would fix this issue elsewhere, requires updates to every field component.

**Comment by charliepark** [comment]
I'm going to start in on this, approaching it as Ben laid out in option #3 above. There are a few UI elements that aren't, strictly speaking, form elements, (tabs, buttons), but they impact the form state, so I'll freeze those as well when `isSubmitting`.
