### ISSUE TITLE
Cancel modal loop

### ISSUE THREAD

**Issue by augustuswm** [oxidecomputer/console#1745]
Encountered a loop when clicking off of the image upload modal. When the right hand upload image form it seems that attempting to cancel out of the alert will retrigger it again. Clicks on other areas of the screen do not seem to exhibit this behavior.

[Screencast from 2023-08-30 21-47-53.webm](https://github.com/oxidecomputer/console/assets/1377730/1ed8573a-39c9-473d-9ba3-3bd9c7dd2ef2)

(looks like cursor didn't get captured, I can recapture if needed)

Running omicron commit ab3591753bc2546bab6f666985dd9e26afa7d3dd

**Comment by augustuswm** [comment]
Also noticed as a part of this that right clicking anywhere outside of the modal triggers the cancel flow.

**Comment by david-crespo** [comment]
Can repro. Nice. Weird. Working on it.

![2023-09-05-modal-loop-repro](https://github.com/oxidecomputer/console/assets/3612203/2813e091-f849-4f8c-b1c4-32f09d3ebd48)
