### ISSUE TITLE
Popovers in modals can overlap modal footer

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#1754]
Not a huge deal because you have to have a tiny window and scroll with a listbox open to see it. The obvious fix of increasing z-index in the footer didn't seem to work for me, not sure what that's about.

> I found one last tiny issue in both `Modal` and `SideModal`, though it's so small and hard to run into (you need a tiny window) that I would be fine logging it as an issue and not fixing it right now. I tried adding a higher z-index to the modal footer and it didn't work. Maybe something about positioning or not sharing a parent or something?

<img width="539" alt="Screenshot 2023-09-06 at 10 20 10 AM" src="https://github.com/oxidecomputer/console/assets/3612203/e42d5fca-2cc6-4367-a50c-d18dd7be6ee2">

<img width="554" alt="Screenshot 2023-09-06 at 10 27 43 AM" src="https://github.com/oxidecomputer/console/assets/3612203/677cc128-91ce-49ac-9e16-ee66cad5a27e">

_Originally posted by @david-crespo in https://github.com/oxidecomputer/console/issues/1747#issuecomment-1708621125_

**Comment by benjaminleonard** [comment]
This is the desired behaviour IMO — in fact part of the reason we switched to a portal based listbox. Otherwise a modal without a lot of content (like the promote image one) cannot accommodate the listbox.

**Comment by david-crespo** [comment]
Love to see it.
