### ISSUE TITLE
login username and password for simulated

### ISSUE THREAD

**Issue by lichuan6** [oxidecomputer/console#1762]
Hi, 

I was trying to login the console in [simulated omicron](https://github.com/oxidecomputer/omicron/blob/main/docs/how-to-run-simulated.adoc), when I open http://127.0.0.1:12220/projects which will redirect to http://127.0.0.1:12220/login/demo-silo/local?redirect_uri=%2Fprojects, what is the username and password in simulated omicron?

Thanks!

**Comment by david-crespo** [comment]
I think it’s either oxide/password or test-privileged/oxide. If neither of those work I’ll get the right answer tomorrow.

**Comment by lichuan6** [comment]
Thanks for the reply @david-crespo .

I have tried both methods, and neither of them works.
<img width="783" alt="Screenshot 2023-09-25 at 07 38 49" src="https://github.com/oxidecomputer/console/assets/74223747/5ee33e31-44bd-4911-b73b-364bc3ea3b9b">

**Comment by david-crespo** [comment]
Ah, for `demo-silo` I believe it's username `demo-privileged`, password `oxide`. I will test this tomorrow as well and think about updating the doc in Omicron.

https://github.com/oxidecomputer/omicron/blob/dfb6853f28404469e3f91f850bc0d39d5c8f3ff0/sled-agent/src/sim/server.rs#L395-L410

**Comment by lichuan6** [comment]
Anywhere I can get device code:

**Comment by david-crespo** [comment]
`oxide auth login` in the CLI should have printed a code in the terminal when it linked you to `/device/verify`. 

https://docs.oxide.computer/cli/guides/quickstart#_logging_in

**Comment by lichuan6** [comment]
It works!
Thanks @david-crespo !
