### ISSUE TITLE
Utilization: Silo usage overview

### ISSUE THREAD

**Issue by benjaminleonard** [oxidecomputer/console#1783]
Presently an operator can pick a silo and check its utilization using the listbox. We'd like a tabular breakdown of usage so that an operator can compare and check utilization across all silos at a glance.

These designs are out of date, but structurally this is what we're looking for:
<img width="1322" alt="image" src="https://github.com/oxidecomputer/console/assets/4020798/22ce3856-776f-4081-b360-2f58ff439afa">

The same component can be used at a silo level to view utilization across projects.

Presently the API does not give us this information in a single response, but we can stub this out by batching the queries and replace them when that's available.

Aiming to get that initial version done for the next release (3).

**Comment by askfongjojo** [comment]
Closed by https://github.com/oxidecomputer/console/pull/1795
