### ISSUE TITLE
Weird GUI behavior when creating disks

### ISSUE THREAD

**Issue by mkeeter** [oxidecomputer/console#1786]
If you change radio button selection while the name is unpopulated, it will ignore your selection and pop up a complaint about the name field.

https://github.com/oxidecomputer/console/assets/745333/23d0fb4b-c0c6-4c56-92f0-6d1067334139

**Comment by david-crespo** [comment]
Almost certainly introduced in #1770, which changed the behavior from validate on value change to validate on blur. Coincidentally we are running into a related issue on #1784 and thinking about how to deal with it.
