### ISSUE TITLE
Want option to display more resources (instances, disks) per page

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/console#1794]
From a customer who came off a demo of the console to internal users:
Is there a way to increase the number of resources (instances, disks) etc listed as a table on various pages? Or could that be dynamic? It would be nice to take better advantage of available screen real estate (especially vertical monitors) and minimize clicks.

**Comment by david-crespo** [comment]
This wouldn't be _that_ bad to make configurable, but we should probably also make the default page size 50 or something.

**Comment by paryhin** [comment]
We do have a design for this in our component library in Figma: 
![CleanShot 2023-10-19 at 23 20 38@2x](https://github.com/oxidecomputer/console/assets/56555905/2c68248d-7a68-4e1e-a17d-3887a1a5aae9)

Would be nice to implement it. https://www.figma.com/file/D5ukCJbedrlGkUIh0E6QtX/Component-Library?type=design&node-id=1116%3A32803&mode=design&t=mFMhOcSPL8YvDPX1-1
