### ISSUE TITLE
Project dropdown box shows only the first 20 projects

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/console#1817]
There are more projects than what is shown in the dropdown:
<img width="1065" alt="image" src="https://github.com/oxidecomputer/console/assets/10874909/d71916b7-d9ac-4850-8e1d-80b9af6a2c74">

This can be confusing for the user when they can't find their project.

If an unbound number of items in the dropdown is a concern, perhaps we can show "More" at the bottom of the list?

**Comment by benjaminleonard** [comment]
We can just set a max height on the dropdown for now. 
We had also worked on a project modal picker that had searching built in, which handles larger project counts a little better.

<img width="1356" alt="image" src="https://github.com/oxidecomputer/console/assets/4020798/ffa08821-f8cf-41d1-8011-32ed2841991b">

**Comment by benjaminleonard** [comment]
Actually just noticing the response is limited to 20 items: https://github.com/oxidecomputer/console/blob/17408f64b1e163e5b03fd441491a984c0a8c3e2d/app/components/TopBarPicker.tsx#L235

**Comment by david-crespo** [comment]
I like the more button idea because while we could increase the page size, there's a real limit to how many things you can reasonably scroll through in that menu.

**Comment by benjaminleonard** [comment]
@david-crespo if we do that we should also increase the page size on the projects page (and perhaps across the board) – 12 might be frustrating if you've got 20+ projects.

**Comment by david-crespo** [comment]
Fixed by #1839 — now we show 200
