### ISSUE TITLE
Select and add SSH keys within instance create form

### ISSUE THREAD

**Issue by benjaminleonard** [oxidecomputer/console#1818]
Console implementation of this [3056](https://github.com/oxidecomputer/omicron/issues/3056) when it is added to Omicron.

> The current implementation automatically [retrieves](https://github.com/oxidecomputer/omicron/blob/6f8cc328740b0f535df01c91efc38108a34edad4/nexus/src/app/instance.rs#L713-L748) and [inserts](https://github.com/oxidecomputer/omicron/blob/6f8cc328740b0f535df01c91efc38108a34edad4/nexus/src/cidata.rs#L17-L36) a user's SSH keys into the instances they create. However, it would be beneficial for users to have control over which keys are added, as well as the ability to pass an SSH key not associated with their account.

> I propose adding an option to the [instance_create](https://docs.oxide.computer/api/instance_create) API that accepts an array of attached SSH keys identified by name or ID, or a custom SSH key provided as a string (which will not be linked to the user's account).

> For an enhanced user experience, we could also include an option that automatically incorporates a user's SSH keys. This would be particularly useful for the CLI, where retrieving SSH keys and adding them as an option is more cumbersome.

> It might be reasonable to defer implementation until after FCS. In the meantime, I could work on adding a console message to inform users that all their SSH keys will be injected into the instance (where cloud-init is supported).

**Comment by david-crespo** [comment]
I'm worried about the checkbox version because it means this section can get arbitrarily tall. In practice maybe not an issue, but it would be good if the box could scroll.

![image](https://github.com/oxidecomputer/console/assets/3612203/6db110a5-db79-43c9-800d-40d0c867833c)

**Comment by david-crespo** [comment]
Love that the checkbox design is very compact but it could get arbitrarily tall unless we put it in a box that can scroll.

![image](https://github.com/oxidecomputer/console/assets/3612203/6db110a5-db79-43c9-800d-40d0c867833c)

**Comment by benjaminleonard** [comment]
Considered a few solutions but perhaps the simplest would be a "More ↓" if there's more than x number of keys.

**Comment by david-crespo** [comment]
Yeah, that works. 99.9% of the time there should not be more than a few keys.

**Comment by charliepark** [comment]
Will assume a "check all / uncheck all" button would be overkill for now, assuming there won't be more than a few keys in most cases, but it could be a nice affordance if we find that's not the case.

**Comment by david-crespo** [comment]
Closed by #1867
