### ISSUE TITLE
Disk size input no longer auto-updates with image change

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#1823]
Most likely introduced with #1582. The disk size input is supposed to update if the image is changed to one that's too big for the current size.

https://github.com/oxidecomputer/console/blob/65ae1212cf3ae120d6605b30deabb35348343295/app/components/form/fields/ImageSelectField.tsx#L32-L39

https://github.com/oxidecomputer/console/assets/3612203/e711c702-e7ec-4705-9eef-c6572d37a59f

**Comment by charliepark** [comment]
Fixed this back in #1829
