### ISSUE TITLE
Show image size on image picker

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#1824]
I'm always wondering about the image size when I look at these. It would be very easy to include. Related to #1777, could fix together.

<img width="567" alt="image" src="https://github.com/oxidecomputer/console/assets/3612203/09a89aae-1a89-4e49-90ed-84b33c7e5d59">

**Comment by charliepark** [comment]
Is this about what we want for the disk size piece of it?
![Screenshot 2023-12-05 at 5 10 24 PM](https://github.com/oxidecomputer/console/assets/22547/fb826437-dbc5-4c50-98eb-301cd2200af3)

**Comment by david-crespo** [comment]
That would do it for me, though seeing it makes me wonder how we should round. I think the mock images are exact GiB multiples, but obviously that’s not true in general. I’m thinking at least one decimal point, maybe two?

**Comment by zephraph** [comment]
One decimal point should definitely be sufficient.
