### ISSUE TITLE
Some projects not available in drop down list

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/console#1838]
As you can see in the screenshot some of the projects are not available in the drop down project list

![Screenshot from 2023-12-07 14-52-04](https://github.com/oxidecomputer/console/assets/7670244/245891b1-e6e2-49f8-8289-2fd45592d8dc)

**Comment by david-crespo** [comment]
Easy: we're only asking for 20.

https://github.com/oxidecomputer/console/blob/a0bf47aaa5e4b431050af486f18d6d5382c82f60/app/components/TopBarPicker.tsx#L234-L235

Experiments [here](https://github.com/oxidecomputer/console/issues/1837#issuecomment-1844373027) suggest that as long as the list can scroll, it should be fine to make the page size quite big. We could start with 100? 200?

**Comment by karencfv** [comment]
Thanks for looking into this so quickly! :bowing_woman:
