### ISSUE TITLE
Typing "oxide" into an instance's serial console renders the echoed text as "0×ide"

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/console#1840]
I was experimenting with logging into a guest image with the username 'oxide' when I noticed something odd:

![oxide-or-oxide](https://github.com/oxidecomputer/console/assets/47763450/51719799-cd98-4ac5-a758-90f5cca3fe0a)

I see that the `<span>` containing the echoed console characters has the right contents, so this seems to be purely stylistic, but it threw me for a loop (the login attempt failed for unrelated reasons, but I had to triple-check that yes, I had, in fact, sent the guest the correct username!).

Is it intended that instance serial consoles render "oxide" this way? I'd venture that this behavior should be suppressed for them. (I looked around for where this substitution was happening and could find neither hide nor hair of it, so I'd be also curious about how it's implemented!)

**Comment by benjaminleonard** [comment]
Whoops. This is an easy fix though, just need to turn the stylistic set off. We do it already elsewhere.
