### ISSUE TITLE
Show (and maybe enforce) allowed formats on image upload form

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/console#1846]
When uploading an image it would be nice to have a small description of which image formats are accepted. Perhaps also a link to https://docs.oxide.computer/guides/creating-and-sharing-images.

Additionally, it's difficult to know which block size to choose. If 512 is the default, perhaps write "default" next to it?

![Screenshot from 2023-12-12 10-27-12](https://github.com/oxidecomputer/console/assets/7670244/191575dd-befb-48b5-91b1-ac8097a82b68)

**Comment by david-crespo** [comment]
Per https://github.com/oxidecomputer/omicron/issues/3559#issuecomment-1915028747, probably also worth doing a check on the filename (or inferred mime type) and rejecting extensions we know won't work.

**Comment by david-crespo** [comment]
Fixed by https://github.com/oxidecomputer/console/pull/2217 and https://github.com/oxidecomputer/console/commit/de7e443f51741bb2949ceab0bdf8ad011869d4bf (link to images doc at the top of the form).
