### ISSUE TITLE
External IP address on instance list and view page

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/console#1849]
The first thing I want to do once I create an instance is connect to it. It'd be nice to have the external IP address as a first class citizen on both list and view pages. It took me a while to figure out where it was.

![Screenshot from 2023-12-12 11-10-05](https://github.com/oxidecomputer/console/assets/7670244/10b447b9-5d4c-44d3-b2d9-2d9aede37872)
![Screenshot from 2023-12-12 11-10-16](https://github.com/oxidecomputer/console/assets/7670244/314a9641-e3fb-4de3-9757-4072b2caff83)

**Comment by charliepark** [comment]
Any thoughts on what would be a useful 8th field for the top of the view page (to balance the two columns)?

**Comment by karencfv** [comment]
Perhaps we can remove `created` ? That's generally information you don't need often

**Comment by charliepark** [comment]
I could see removing `created`, or possibly keeping it and adding `last updated` to go with it.
