### ISSUE TITLE
[polish] Image select without os/version

### ISSUE THREAD

**Issue by augustuswm** [oxidecomputer/console#1856]
![image](https://github.com/oxidecomputer/console/assets/1377730/d2c4b1ae-7254-44e5-9c00-a7db9cf07884)

If an image does not have an os / version set, the empty strings are still rendered. In the API response these appear as:

```
{
  "os": "",
  "version": ""
}
```

**Comment by david-crespo** [comment]
Fixed in #1836, not yet out on colo.
