### ISSUE TITLE
Utilization Summary: Available quantity of resources should be kept to two decimals 

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/console#1864]
The large number of decimals seem to show up only in the available storage column but please ensure all numbers in the table are handled in the same way.

<img width="1260" alt="image" src="https://github.com/oxidecomputer/console/assets/10874909/f3aaf930-1813-48c0-b8b0-e64cb587bc46">

**Comment by david-crespo** [comment]
fucking JAVASCRIPT

**Comment by david-crespo** [comment]
By which I mean: we didn’t forget to round, our stupid round function has the ability to do that because of floats. Ugh.

https://github.com/oxidecomputer/console/blob/ad2ea54a27615e21a4993fbeff3fd83fbc2098a4/libs/util/math.ts#L18-L21
