### ISSUE TITLE
Instance disk metrics should not be displayed in bytes

### ISSUE THREAD

**Issue by Aaron-Hartwig** [oxidecomputer/console#1866]
I'm seeing raw counts of things like number of/bytes for reads/writes. I'm assuming this is not the design intent given those raw numbers aren't really that useful and it also is not how we display `/utilization`.

![image](https://github.com/oxidecomputer/console/assets/5115774/1abc370c-0735-4d69-8ec7-46a6713ab931)

Is there supposed to be some sort of dynamic unit selection here?

Also, when I resize my browser those Y-axis labels continue to run outside the box (sorry I don't know the technical word here). I guess I'd have expected the chart to scale more dynamically, perhaps some % of new width would be allocated to the axis labels and the rest to the graph itself.

**Comment by david-crespo** [comment]
We are being very unsmart here, just jamming the data directly into the chart without any transformation.

https://github.com/oxidecomputer/console/blob/02c6ce747fd5dd05e9d454ecb1bf70392c9d954e/app/pages/project/instances/instance/tabs/MetricsTab.tsx#L47-L81

Compare to utilization tables, where we explicitly transform to a hard-coded unit:

https://github.com/oxidecomputer/console/blob/02c6ce747fd5dd05e9d454ecb1bf70392c9d954e/app/pages/SiloUtilizationPage.tsx#L104-L117

Obviously we should do something similar here. The main open question for me is whether we should hard-code a unit like we do above — presumably `MiB` or `GiB` — or do we need to be more clever based on the order of magnitude of the data we're seeing (if this data tends to vary over a pretty wide range).

**Comment by bnaecker** [comment]
The usual trick with this kind of data is to divide it by 10 so that it’s always between one inclusive and 1000 exclusive. Each time you divide you move up by one SI prefix, so you start with bytes, then KiB, then MiB, etc., 00 rounding to one or two decimal places.
