### ISSUE TITLE
Metrics pages fail when browser timezone is incorrect

### ISSUE THREAD

**Issue by augustuswm** [oxidecomputer/console#1875]
If a browser reports a timezone that the console is unable to handle (i.e. `Etc/Unknown`), the console will fail with the `Something went wrong` error page. The reported error in devtools is:

```
react-dom.production.min.js:189 RangeError: Invalid time zone specified: Etc/Unknown
    at new DateTimeFormat (<anonymous>)
    at YP (import.mjs:2516:27)
    at new bs (import.mjs:2480:26)
    at Object.formatValue (import.mjs:1148:34)
    at $H (import.mjs:1517:23)
    at QH (DateRangePicker.tsx:31:5)
    at mw (react-dom.production.min.js:167:137)
    at A6 (react-dom.production.min.js:290:337)
    at T6 (react-dom.production.min.js:280:389)
    at d_ (react-dom.production.min.js:280:320) 
```

This occurs on both the Fleet utilization page as well as the instance metrics page. We probably should fail with a more graceful error message.

**Comment by augustuswm** [comment]
Completely agree, UTC with a visible timezone indicator makes sense. As for how I got in to this state... I am still trying to figure that out myself.

**Comment by david-crespo** [comment]
I think [this](https://github.com/adobe/react-spectrum/blob/4ae2831f9487958511c88b9ebe672b5650042d7e/packages/%40react-stately/datepicker/src/useDatePickerState.ts#L182-L190) is the `formatValue` in the trace. That calls `new DateFormatter` (`new bs` in the trace), defined [here](https://github.com/adobe/react-spectrum/blob/4ae2831f9487958511c88b9ebe672b5650042d7e/packages/%40internationalized/date/src/DateFormatter.ts#L24), which calls [`getCachedDateFormatter`](https://github.com/adobe/react-spectrum/blob/4ae2831f9487958511c88b9ebe672b5650042d7e/packages/%40internationalized/date/src/DateFormatter.ts#L123C10-L123C32) (`YP` in the trace), which calls the built-in `Intl.DateTimeFormat` [here](https://github.com/adobe/react-spectrum/blob/4ae2831f9487958511c88b9ebe672b5650042d7e/packages/%40internationalized/date/src/DateFormatter.ts#L139) to get that error. That's probably more detail than we need, but I wanted to track down where the call comes from.

You can reproduce the error easily in the browser console.

<img width="614" alt="image" src="https://github.com/oxidecomputer/console/assets/3612203/a6604325-1a44-4dc0-9d49-0120cb5e04da">

I do see other people running into this `Etc/Unknown` TZ sometimes, but it seems like a rare system bug that we can't do much about. People (including @augustuswm) report it going away on restart. I'm leaning toward `wontfix`.

https://support.google.com/chrome/thread/230621092/chrome-version-116-displaying-wrong-timezone-on-linux-computers?hl=en
https://github.com/dagster-io/dagster/discussions/18709
