### ISSUE TITLE
Need way to log out from error screen

### ISSUE THREAD

**Issue by augustuswm** [oxidecomputer/console#1876]
If you log in to a silo, in which you do not have permissions assign to you, you will be presented with the "Something went wrong" screen. This screen does not have the mini-dropdown menu (containing the username and logout action). To actually logout the user currently needs to delete their session cookie or do some inspection of internal routes.

**Comment by benjaminleonard** [comment]
I'm not sure where we could take the user instead if they don't have access. I guess we either show a specific – "you don't have the right permissions to be here" screen with a logout or if the user doesn't have a minimum level of permission just kick them back out and don't save their session cookie with some kind of notice on the login screen.

**Comment by david-crespo** [comment]
Thanks for the bump. Maybe we can just add a logout button to that screen — it's probably weird to have it on the generic error page all the time, so maybe there's a way we can detect this situation. We can't actually hit `/session/me` in that case to get the username or other info, can we? What does the API error look like when you try to make requests? Does is it a weird 401? A 403 on everything?

**Comment by dwradcliffe** [comment]
We ran into this a bunch of times getting new users setup, so either of the proposed fixes would be helpful :)
