### ISSUE TITLE
Side modals do not animate in on the VPC sub-pages

### ISSUE THREAD

**Issue by benjaminleonard** [oxidecomputer/console#1889]
They appear instantaneously. At first I thought it might be something to do with the fact the other modals are navigated to through the router but the new disk page on the instance page seems to animate in just fine.

![CleanShot 2024-01-16 at 10 03 43](https://github.com/oxidecomputer/console/assets/4020798/6c37cb7c-2763-4d13-9ccd-fc284314acae)

**Comment by benjaminleonard** [comment]
https://github.com/oxidecomputer/console/blob/ca7c85de20f750a7444e8895e25b6368493483aa/app/components/form/SideModalForm.tsx#L45-L47

Here's the responsible line – new firewall rule is not it's own route and therefore does not animate. Perhaps related to #1913 since I am guessing we can't keep the tab as a param and have the modal as a route.

**Comment by david-crespo** [comment]
Fixed by #2249
