### ISSUE TITLE
Clicking on a tooltip scrolls me to some other validation error

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#1902]
I have no guess as to what's going on. Not very high priority because nothing is fundamentall broken by this. It's just weird and a little annoying. Not even sure if it's specific to this form, but I doubt it.

https://console-hd3syls16-oxidecomputer.vercel.app/projects/mock-project/instances-new

https://github.com/oxidecomputer/console/assets/3612203/9a0e26c5-fc93-4a8f-873c-3ad60b6d28bb

**Comment by benjaminleonard** [comment]
lol
![CleanShot 2024-01-30 at 11 23 59](https://github.com/oxidecomputer/console/assets/4020798/43ce9cc5-d3b4-4623-9351-b5cbd3ca3266)
