### ISSUE TITLE
Pressing enter in firewall rule "subforms" should not submit full form

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#1919]
I instinctively press enter when trying to add a target or host, expecting it to be equivalent to clicking the add button, but instead it submits the whole form, which is very frustrating. This is especially bad because it can be hard to tell what you did and didn't change.

<img width="484" alt="image" src="https://github.com/oxidecomputer/console/assets/3612203/13a1b22b-4b7e-4d90-b578-e74ac9a2eed6">

**Comment by charliepark** [comment]
I'm having trouble replicating this issue, on either Firefox or Chrome. I think I'm following the described flow using the enter key as often as I can (highlight `Host type` input and hit enter to get dropdown; arrow key down/up to select one; hit enter to select; tab to next field; type in a string; tab to `Add host filter` button; hit enter → it adds a new host filter line; focus is still on button with now-emptied form, and I can tab from there onto the newly-created host line). Happy to try again if I'm missing a step in the bug replication.

**Comment by david-crespo** [comment]
I'm hitting enter while still in the value field, not tabbing to the button.
