### ISSUE TITLE
Keep error toasts around longer

### ISSUE THREAD

**Issue by augustuswm** [oxidecomputer/console#1945]
Suggestion for a change in behavior on some of the error toasts:

Ran in to this when cleaning up failed instances. Toasts can be easy to miss, especially if you want to copy data out of them. When an unexpected error occurs (i.e. Internal Server Error or something similar) it would be useful for:

1. The toast to remain visible until the user manually clears it
2. Possibly display the `request_id`?

The request id is currently only usable internally by us, but eventually it could be a useful piece of data to be able to capture for support tickets in the future.

I don't think this would need to apply for things that are user error, or expected errors.

**Comment by benjaminleonard** [comment]
First one seems like a reasonable behaviour for error toasts.
If it isn't already, perhaps we log the `request_id` to the console. I know you can grab it in the request.

I don't think we should make it visible in the UI, it gives it undue prominence.
