### ISSUE TITLE
Disk snapshot of "Stopping" instance fails silently

### ISSUE THREAD

**Issue by augustuswm** [oxidecomputer/console#1961]
To reproduce:
1. Request that an instance be stopped
2. Go to the Disks page of the project
3. Attempt to take a snapshot of the disk attached to the instace
4. You will receive a prompt that a snapshot is being created
5. No error message will appear despite the request failing with a 400 error that reports the error

Similar (possibly needs the same fixes as #1947)

**Comment by augustuswm** [comment]
Perfect, I assume this will go in to the next dogfood build? I can check it later this week.

**Comment by david-crespo** [comment]
Yes. Regardless of whether we've bumped console in Omicron by then, I will manually bump dogfood with the latest console after the deploy.
