### ISSUE TITLE
List floating IPs more clearly on single instance page

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#1965]
Followup to #1957 

You can see external IPs here in the properties table, but we don't distinguish between ephemeral and floating and there's no link back to the floating IPs page. I think it might make sense to add a tab for a floating IPs table. Or actually... how about all IPs whether floating or ephemeral.

<img width="990" alt="image" src="https://github.com/oxidecomputer/console/assets/3612203/23724c7b-cd75-4dfd-bee0-ab9ded581081">

**Comment by benjaminleonard** [comment]
> Currently, we're listing in the properties table. We should also display them in a regular table in the "Network Interfaces" tab (to be renamed to "Networking").

Was thinking this as an approach instead – though perhaps blocked by #1988. I think more sustainable to group by section rather than a tab for each resource.

> This lets us show: the source and type of the IP address (is it ephemeral or floating), provides additional context (e.g. name and description), and lets the user do some actions inline (e.g. detaching a floating IP).

**Comment by charliepark** [comment]
This screenshot was added to Linear but didn't sync over here, apparently:
![image](https://github.com/oxidecomputer/console/assets/22547/859b822a-4f44-4679-b03f-dd84f5bcd65e)

**Comment by david-crespo** [comment]
Even their notes look nice!

**Comment by charliepark** [comment]
Just capturing a few screenshots from Figma here.
<img width="823" alt="Screenshot 2024-04-02 at 4 19 59 PM" src="https://github.com/oxidecomputer/console/assets/22547/4b88812e-bc61-44f2-82cd-31bff045bf46">
<img width="820" alt="Screenshot 2024-04-02 at 4 21 09 PM" src="https://github.com/oxidecomputer/console/assets/22547/b9e456eb-2f9b-49fb-b851-1cec2b4ea9c9">
<img width="829" alt="Screenshot 2024-04-02 at 4 21 32 PM" src="https://github.com/oxidecomputer/console/assets/22547/ae21c3b0-d983-4b01-9618-a65110153a76">
<img width="820" alt="Screenshot 2024-04-02 at 4 21 46 PM" src="https://github.com/oxidecomputer/console/assets/22547/b3255825-2e72-4302-81ba-2fd9b9d8e31a">
