### ISSUE TITLE
`Instances` in sidebar not highlighted on instance create page

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#2038]
Instance create is `/projects/mock-project/instances-new` and the sidebar link is `/projects/mock-project/instances`.

![image](https://uploads.linear.app/b7545512-bb0c-4743-adc4-e5797212a353/de35d8ef-c4c7-4a48-a287-a844efc19c58/4dd10308-8311-4f25-bf2b-b87f1a89830c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2I3NTQ1NTEyLWJiMGMtNDc0My1hZGM0LWU1Nzk3MjEyYTM1My9kZTM1ZDhlZi1jNGM3LTRhNDgtYTI4Ny1hODQ0ZWZjMTljNTgvNGRkMTAzMDgtODMxMS00ZjI1LWJmMmItYjg3ZjFhODk4MzBjIiwiaWF0IjoxNzA5NzQ0NjAzLCJleHAiOjMzMjgwMzA0NjAzfQ.\_exdocnMOQThCJmCe0lZMSS6TsE-mcBYM7yRrXI2RTE "=825x")

**Comment by benjaminleonard** [comment]
Can we use `/instances/new` for this – to match `/edit` in other paths?

**Comment by david-crespo** [comment]
We can't because there could be an instance named `new`. `/edit` works because it is after the instance name.

**Comment by benjaminleonard** [comment]
Ah I vaguely remembered there was a reason for it.
