### ISSUE TITLE
Create standard component for "descriptive copy above a table"

### ISSUE THREAD

**Issue by charliepark** [oxidecomputer/console#2056]
We currently have a few places where we use `<p className="mr-8 max-w-2xl text-sans-md text-secondary">` (or a close variation; check!), and we should standardize that and just pass in / wrap ReactNode contents.

**Comment by paryhin** [comment]
As a temporary solution, this is fine, but we should avoid having descriptive copy in the page body. Some components can have it, like input fields, but tables and other major elements are not the best candidates for it.  It quickly becomes annoying and intrusive for returning users, and takes valuable space.  A better solution would be to use a component that can be hidden / activated by the user as needed. One of the earlier ideas was to have a context-aware documents/help button that takes the user to the relevant documentation or, even better, displays it in the context, e.g. side pane. A good example can be found in the onboarding designs: https://www.figma.com/file/BoYtmMvwwNqs6lkLisptT6/Onboarding?type=design&node-id=2181%3A32809&mode=design&t=W21RKr72asPhmWqY-1
