### ISSUE TITLE
Poll instance state

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#2095]
Very apt and evocative description of the problem from @iliana:

> something about the flow of starting an existing instance, waiting for it to go from starting -> running so that i can successfully look at the serial console, or waiting for it to go from stopping -> stopped so i can start it again or delete it is kind of frustrating; i find myself repeatedly refreshing the page at the browser level because i don't see a button to refresh the data in the console, and also because there seems to be a lag time between when an instance is actually stopped, and when the console knows.

I have experienced this myself. I think the fix here is simply to poll, and make very clear when we are polling. If we are not clear enough, then users will expect every page to be polling live or at least be unsure whether to expect it. 

A maybe less nerve-wracking fix would be to sprinkle more refresh buttons around, like we have on the instance list. We could also stand to have a better UI treatment when you click refresh, because when I click it and nothing changes, I feel like maybe nothing happened. In places we have space, we could add a little message next to the button saying when it was last refreshed, or maybe we could do that in a tooltip, which would not have any space requirements.

<img width="822" alt="image" src="https://github.com/oxidecomputer/console/assets/3612203/44268397-a245-4d66-b176-684c5e0e9b0a">

**Comment by iliana** [comment]
Also if we want to be clever here (I don't know if it is necessarily a good idea to be clever), we could use the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) to quiesce polling if the tab is not visible (e.g. not the active tab).

**Comment by david-crespo** [comment]
We may get this cleverness for free. The docs could be clearer here, but I think React Query use that API automatically to pause refetches when the tab is in the background.

https://tanstack.com/query/latest/docs/framework/react/reference/useQuery

<img width="771" alt="image" src="https://github.com/oxidecomputer/console/assets/3612203/78ccacb3-977f-47e8-980f-c8ef589fae9a">

**Comment by david-crespo** [comment]
Added a refresh button in https://github.com/oxidecomputer/console/pull/2159. Changed the title here to reflect the more interesting solution, polling, and moved to milestone 9.
