### ISSUE TITLE
Firewall rules table: use + popup for overflow when there are too many targets/filters

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#2118]
Right now they stack and can overflow the cell.

**Comment by benjaminleonard** [comment]
Do we want to make this a generic cell component that can handle overflow + popup? We've got it in a few places.

**Comment by david-crespo** [comment]
We sort of have that already. We take the first child and show it in the cell and put the rest in the popup. I wouldn't want to make it smarter than that because that logic about what to put in cell vs. popup seems pretty specific to each call site.

https://github.com/oxidecomputer/console/blob/7383152dea1cabcc356fccf979e62bd74ac8ef68/app/components/ListPlusCell.tsx
