### ISSUE TITLE
Show more data about physical disks

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#2124]
In https://github.com/oxidecomputer/omicron/issues/5153, the API added `state` and `policy` fields to physical disks. We should probably show at least state in the table, if not also policy. `timeModified` might also be useful if it reflects when the state last changed. I also think could stand to add a detail view in a side modal that you get to by clicking the ID cell, and which would include more or less all the fields in a properties table.

<img width="1183" alt="image" src="https://github.com/oxidecomputer/console/assets/3612203/331231fe-d587-4f06-b365-60d0faf92d81">

**Comment by smklein** [comment]
Although we haven't exposed an API for it directly yet, the intent is that operators will be able to control the `policy` for physical disks. This is the mechanism by which an operator can observe a physical disk, decide it should not be used, and "expunge" it.

The `state` field of physical disk lags behind, as it's controlled by Nexus. The common case here will be:

- Policy: In-Service, State: Active  -- (Normal operating conditions)
- Policy: Expunged, State: Active  -- (Operator requests either the disk is no longer used, or does the same for the sled containing this disk)
- Policy: Expunged, State: Decommissioned  -- (Follow-up from prior state, where Nexus has finished the necessary clean-up work).

There will be more states later with graceful removal, but I expect that'll be the typical flow.

**Comment by david-crespo** [comment]
Ok, great. so we definitely want both columns in the table.
