### ISSUE TITLE
floating-ip creation fails with "Not found: ip-pool with name" when selecting ip-pool

### ISSUE THREAD

**Issue by taspelund** [oxidecomputer/console#2135]
Floating IP creation fails if an optional IP Pool is supplied:

![image](https://github.com/oxidecomputer/console/assets/15963272/6b5c7c97-6744-44df-b216-2811b06d3817)

This happens on colo both when selecting `default` or `sandbox` IP Pools from the drop-down, but not when leaving the IP Pool selection empty.

**Comment by taspelund** [comment]
This happens even when `IP address (Optional)` is not populated

**Comment by benjaminleonard** [comment]
Interesting, succeeded on dogfood with this payload – can investigate further on colo:

```
{ip: "172.20.26.253", name: "test", description: "", pool: "default"}
```

**Comment by david-crespo** [comment]
I'll take a look at what we're doing API side. Thanks!

**Comment by david-crespo** [comment]
Moved to Omicron: https://github.com/oxidecomputer/omicron/issues/5508
