### ISSUE TITLE
View and update quotas from silo detail

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#2143]
Weird that you can't see or update quotas on this view. You can only see them on utilization and you can't update them anywhere.

<img width="1092" alt="image" src="https://github.com/oxidecomputer/console/assets/3612203/a503d7f6-1600-4121-b838-c289ff68e10c">

**Comment by paryhin** [comment]
I've added a couple of screens to the Utilization Figma flow that should address this. Happy to chat about it. 

https://www.figma.com/file/GxsrGUQkWwDg6LuiWM9Rft/Capacity-%26-Utilization-v2?type=design&node-id=2064%3A9935&mode=design&t=hHz01NWPQZYAwwXu-1

**Comment by paryhin** [comment]
<img width="1440" alt="update-quota" src="https://github.com/oxidecomputer/console/assets/56555905/09366dcf-4362-4772-a594-999676e3d777">

**Comment by david-crespo** [comment]
I don't think we're getting to this for v9, but we should do it in v10.

**Comment by augustuswm** [comment]
Ran in to this a few times within the last couple weeks. Very much looking forward to it!
