### ISSUE TITLE
Serial console shows "Connected" when instance is not running

### ISSUE THREAD

**Issue by iliana** [oxidecomputer/console#2169]
I have an instance that is stopped. When I navigate to its serial console in the console, it shows a blank terminal (as one would expect), but also "Connected" in the lower right. No errors display.

When I try to do the same thing in the CLI, I get:

```
$ oxide instance serial console --project iliana --instance axiomatic

Connection closed: Error
Server error: Invalid Request: instance is stopped and has no active serial console server
```

**Comment by david-crespo** [comment]
We're displaying the status we think it is, so there must be something wrong with our error handling:

https://github.com/oxidecomputer/console/blob/629c94a6d393e09cd3eb1a5e78a201da592cfb79/app/pages/project/instances/instance/SerialConsolePage.tsx#L83-L97

https://github.com/oxidecomputer/console/blob/629c94a6d393e09cd3eb1a5e78a201da592cfb79/app/pages/project/instances/instance/SerialConsolePage.tsx#L121-L123

**Comment by iliana** [comment]
I don't know that Firefox is seeing the error; it's not showing up in the network console at all where you can usually observe the websocket traffic. Here's one from the serial console of a running instance:

![image](https://github.com/oxidecomputer/console/assets/52814/06a75561-7fc1-47d1-8d17-bc365204b235)

But when connecting to a stopped instance I see no messages whatsoever.

**Comment by david-crespo** [comment]
The CLI isn't doing anything too exciting.

https://github.com/oxidecomputer/oxide.rs/blob/bc90ca23109b9e699472bdda4867e4f93d18da1a/cli/src/cmd_instance.rs#L109-L129

The error message you see in the CLI comes from an error response from the API — maybe we're ignore errors on the initial attempt to upgrade the connection? Or maybe something stranger is happening and API is handling the request from the browser differently.

https://github.com/oxidecomputer/omicron/blob/77fffe5e3492c471f9fd176d54e9cdce51c6e0ff/nexus/src/app/instance.rs#L1828-L1833

**Comment by david-crespo** [comment]
When I connect to a stopped instance I get a 101, which I guess we take as a kind of success, and then nothing else. Will need to look closer at what the CLI is doing to get that error.

<img width="628" alt="image" src="https://github.com/oxidecomputer/console/assets/3612203/6189d1ff-7d8d-47fa-abeb-42a1480691ed">

**Comment by lifning** [comment]
our websocket endpoints unconditionally upgrade (101) -- the thing to look for is a websocket Close message, with the relevant error message appearing as a [Close Code](https://www.rfc-editor.org/rfc/rfc6455.html#section-7.1.5).

**Comment by david-crespo** [comment]
Thanks @lifning, that was exactly what I needed to hear. Notice anything just very slightly off here?

https://github.com/oxidecomputer/console/blob/629c94a6d393e09cd3eb1a5e78a201da592cfb79/app/pages/project/instances/instance/SerialConsolePage.tsx#L89

https://developer.mozilla.org/en-US/docs/Web/API/WebSocket#events
