### ISSUE TITLE
Say something clearer than nCPUs in the UI

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#2195]
We got it from the API but that's no reason to confuse people.

![image](https://github.com/oxidecomputer/console/assets/3612203/d6321d14-ea2e-41b4-b621-171601b12105)

https://github.com/search?q=repo%3Aoxidecomputer%2Fconsole+ncpus&type=code

**Comment by charliepark** [comment]
I think the one other place we use `nCPUs` is in the silo create form:
<img width="477" alt="Screenshot 2024-04-24 at 5 50 10 PM" src="https://github.com/oxidecomputer/console/assets/22547/69381c7a-c27f-459f-9dba-26d6ef73a186">

We could use `(COUNT)` (or `(count)`? `(Count)`?) in the capacity chart. In the silo create form, maybe we don't need a sublabel?
