### ISSUE TITLE
Animate `DocsPopover`

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#2210]
I don't want to block #2194 on this because it's already great without an animation, but I think an animation would be nice and it would match how dropdown menu works. Apparently we do it in CSS:

https://github.com/oxidecomputer/console/blob/042d5ef3036563967b1b58cea2cffe47df11151f/app/ui/styles/components/menu-button.css#L36-L55

**Comment by benjaminleonard** [comment]
We can reuse the dropdown animation if it's an easy addition. I was planning to do a bit of an animation audit and overhaul in the coming weeks so if it hasn't been done by then I'll take a look.
