### ISSUE TITLE
Docs popover on SSH keys page

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#2211]
Not sure we have a good doc to link to, so this may be conditional on making such a doc.

**Comment by charliepark** [comment]
Best I've found is at https://docs.oxide.computer/guides/quickstart#_appendix, but … we should have a more robust doc.

**Comment by charliepark** [comment]
new doc just¹ dropped https://docs.oxide.computer/guides/user-settings#manage-ssh-keys

¹ maybe not "just"

Either way, will get this in there.
