### ISSUE TITLE
Missing empty state for instance external IPs

### ISSUE THREAD

**Issue by benjaminleonard** [oxidecomputer/console#2213]
![image](https://github.com/oxidecomputer/console/assets/4020798/a6b2d20a-ede1-41f2-baea-85966b45e3b1)

We should be using the empty state component with a CTA to attach a floating IP or allocate an ephemeral one.

**Comment by charliepark** [comment]
I fixed this in the ephemeral IP detach/attach work last week.

<img width="1225" alt="Screenshot 2024-07-02 at 2 32 01 PM" src="https://github.com/oxidecomputer/console/assets/22547/98f3032a-86fd-40c6-8dfb-3420f7f52638">
