### ISSUE TITLE
Creating a new firewall rule with the same name overwrites original

### ISSUE THREAD

**Issue by benjaminleonard** [oxidecomputer/console#2220]
Tested on both the mock API and colo.

A side effect that we work with the entire firewall rules object rather than individual rules in the API. We should prevent the user from creating a new rule with a duplicate name.

This does strike me as another downside to the current API, requiring extra logic on the client like this.

**Comment by david-crespo** [comment]
https://github.com/oxidecomputer/console/blob/a06d8521a1e069a9d2c1a387077fa8c3830c0d4e/app/forms/firewall-rules-create.tsx#L558-L562
