### ISSUE TITLE
already-attached disks are listed in disks-to-attach modal in instance create form

### ISSUE THREAD

**Issue by charliepark** [oxidecomputer/console#2254]
In the instance-create form, we give the user the ability to attach existing disks. We should make sure that any disks that have been already selected for attachment aren't available to be selected again. Currently, they aren't filtered out, so can be selected multiple times.
<img width="1263" alt="Screenshot 2024-05-21 at 10 41 47 AM" src="https://github.com/oxidecomputer/console/assets/22547/a534eb21-632f-4b50-9bfc-72dd8a5dd36a">

**Comment by charliepark** [comment]
While fixing this, we can also disable the "attach existing disk" button unless there are available-and-uncommitted disks.

**Comment by david-crespo** [comment]
Ha, check out what I just found at the very bottom of my to do list. Created a year ago almost to the day. I need to make sure all my to dos have issues.

![Screenshot 2024-05-24 at 11 38 37 PM](https://github.com/oxidecomputer/console/assets/3612203/dc26000f-9078-41cc-b4f8-b72a0cbadb17)
