### ISSUE TITLE
Instance networking: attach ephemeral IP button

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#2288]
We're adding ephemeral IP detach in #2285. An attach ephemeral IP button would make sense next to the floating IP button. There is a max of 1 ephemeral IP per instance ([nexus source](https://github.com/oxidecomputer/omicron/blob/895f2800ad96b51c538ae8011df3654d511563c5/nexus/src/app/mod.rs#L104)), so we should disable the button whenever there is already an ephemeral IP.

<img width="857" alt="image" src="https://github.com/oxidecomputer/console/assets/3612203/0dfaca18-8c43-4be9-aaff-3f4b53457a0e">

**Comment by charliepark** [comment]
Factor in #2277, which notes that
>External IP option is a no-op if user has chosen "none" for network interface.
