### ISSUE TITLE
Truncation tooltip on long project name in top bar picker is obscured

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#2327]
<img width="641" alt="image" src="https://github.com/user-attachments/assets/f904adef-da68-49a0-8aca-2686c6a4cf70">

**Comment by charliepark** [comment]
Do we need the truncation here? It might be fine to replace the `<Truncate>` element [here](https://github.com/oxidecomputer/console/blob/main/app/components/TopBarPicker.tsx#L122) with just the `{label}`, to get something like this (with a few other small layout adjustments):
<img width="516" alt="Screenshot 2024-07-17 at 11 45 03 AM" src="https://github.com/user-attachments/assets/5cbc1097-dcbe-4e6b-ba52-d76cea9bce37">


I'm not sure the constrained menu width here is better than just showing the full name of the resource.

**Comment by david-crespo** [comment]
Definitely plausible. The longest name is 63 chars. We'd probably still want to truncate on mobile, barf. But we can worry about that in the mobile PR.
