### ISSUE TITLE
Make system/silo switching more discoverable

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#2356]
This has bothered me for a while, but seeing this WIP on the router page breadcrumbs made me realize there is a huge problem with what we have. The other pickers are for switching between things of a kind: projects, VPCs, routers. Based on that, any reasonable person would infer that the silo picker is a silo picker. Well, it's not. You can't switch silos, that's not a thing. That picker is how you switch to the system-level pages if you have fleet viewer permissions.

<img width="654" alt="image" src="https://github.com/user-attachments/assets/4a592327-9fe9-40ba-be4a-ac7a49b00787">

I was thinking it would make more sense to have the system/silo switcher elsewhere, maybe in the user dropdown menu. That's probably where I would look for something like that.

<img width="208" alt="image" src="https://github.com/user-attachments/assets/047364ab-8de8-4fb0-bcbb-a0fd2765a53b">

I could also picture it being a dedicated link somewhere in the sidebar.

**Comment by charliepark** [comment]
Closed by #2544 
![Image](https://github.com/user-attachments/assets/980ae732-21d4-49c1-9560-631e94693f43)
