### ISSUE TITLE
Subnet: Show linked custom router

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/console#2379]
The optional `custom_router_id` attribute is a key piece of information for the VPC router feature. It'll be very useful to show the name of the router in the subnet table.

**Comment by askfongjojo** [comment]
Two other possible behavior enabled once we show the custom router:
1. The custom router name can have a link to navigate user to the router page.
2. The "edit" popup allows user to set/unset the custom router value.

**Comment by david-crespo** [comment]
Custom router has to exist at subnet create/update time, so the input should be a listbox.

https://github.com/oxidecomputer/omicron/blob/6dd980251a26430466bcd5aff1edad5416cf94e5/nexus/src/app/vpc_subnet.rs?plain=1#L311-L324

**Comment by charliepark** [comment]
A few notes to self:
- will go in subnet-create and subnet-edit
- we'll need to clear the value; what should UI look for that?
- field label: "Custom router name"
- combobx or dropdown, but will need to be an existing custom router for the backend to handle it; API will catch this, so probably don't need to add specific validation
- router should be editable in subnet-edit, so they can switch to a different custom router

**Comment by charliepark** [comment]
(Got confirmation from Angela that many subnets can have the same custom router listed, so we _don't_ need to prune the list based on already-committed routers.)
