### ISSUE TITLE
Instance page breadcrumb needs a dropdown selector

### ISSUE THREAD

**Issue by charliepark** [oxidecomputer/console#2380]
When on an instance page, you should be able to select other instances from that project.

![image](https://github.com/user-attachments/assets/2f5f141e-37e5-4f22-b514-c08131fb2d9a)

**Comment by benjaminleonard** [comment]
Some kind of integrated combobox is probably useful, we'll also want some way to get back to the list page.

<img width="279" alt="image" src="https://github.com/user-attachments/assets/e0144411-8e70-43c8-af64-dbc3f29dfb0e">

Have discussed that we probably need to consider the breadcrumbs a little more, it might be the visual treatment, but often people do not realise they are breadcrumbs at all.

**Comment by paryhin** [comment]
![CleanShot 2024-08-20 at 01 14 25@2x](https://github.com/user-attachments/assets/7dbf7909-fedb-4699-9b83-0a53f0638662)
I have some initial ideas in this file:  https://www.figma.com/design/zlhgBnPivrzeJ3wpIOI5Om/Navigation?node-id=2016-35341&t=6agQxTcMEOBXsXlx-1

**Comment by charliepark** [comment]
Definitely interested in exploring some of those ideas. In order to get the dropdown into v10, I have #2392, and we can absolutely build on that with a more robust breadcrumb solution.
