### ISSUE TITLE
Instance networking tab to support add/remove transit IPs

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/console#2381]
The use of transit IPs is a special use case of custom routes, illustrated in [Example 4](https://docs.oxide.computer/guides/configuring-guest-networking#_example_4_software_routing_tunnels) of the Networking guide. The optional array attribute `transit_ips` defines which target IPs (of other instances in the same subnet) will have their packets re-routed to the instance linked to these IPs.

**Comment by david-crespo** [comment]
Pretty straightforward, just a list on the NIC.

https://github.com/oxidecomputer/console/blob/e442f6bde08082a7b81cf03e16b977435dad99b0/app/api/__generated__/Api.ts#L1904-L1915
