### ISSUE TITLE
Use disabled icon for "disabled" VPC firewall rules

### ISSUE THREAD

**Issue by charliepark** [oxidecomputer/console#2397]
Right now both "enabled" and "disabled" have a check icon. We should update the disabled one to … something else. CC @benjaminleonard 

<img width="1216" alt="Screenshot 2024-08-26 at 3 17 29 PM" src="https://github.com/user-attachments/assets/07343337-4aa3-4c21-abe6-b024abf73550">

**Comment by benjaminleonard** [comment]
See equivalent design for disks. If that isn't already using this icon it should also be:

<img width="437" alt="image" src="https://github.com/user-attachments/assets/864761fe-0697-4e3a-b151-b6a237ee995c">

**Comment by charliepark** [comment]
There are a number of other disk state options … are there specific icons we should be using for the other states? Or we could lean on `<Success12Icon>` and `<Disabled12Icon>` for `attached`/`detached`, and anything else gets `<Info12Icon>` for now?
