### ISSUE TITLE
Internet gateways tab on VPC page

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#2402]
Following https://github.com/oxidecomputer/omicron/pull/6475

**Comment by charliepark** [comment]
Current projection is that that PR (#6475) will be "in good shape" on Monday, 2024-10-30.

**Comment by charliepark** [comment]
Although we have a good start towards this work in #2488, there are a few questions we have about what users would find useful in the Internet Gateway views, and we were stabbing a bit in the dark. I'll connect with Ry and Augustus to get some more insights on what elements of the UI are critical, nice to have, or must-leave-out, as well as the mental model people have as they approach the Internet Gateway x IP Address and IP Pool relationships. Will get the UI for internet gateways in on v12.
