### ISSUE TITLE
instance creation errors can be hard to notice on wide displays

### ISSUE THREAD

**Issue by iximeow** [oxidecomputer/console#2403]
i tried to create a semi-bogus instance to check how conflicting disk names would get handled, and noticed this in the process.. 

![Selection_999(340)](https://github.com/user-attachments/assets/a5a2196a-eea9-4433-af0f-79c8de68ba0e)

i'd named the boot disk `conflict`, configured an additional 10GiB disk named `conflict`, and a NIC named `conflict` for good measure. then scrolled down, hit "Create instance", waited for the spinner to finish spinning, then this is what i saw.

now that i know to look at the bottom right, `DISK NAME ALREADY EXISTS` is clear enough - but i actually found it by opening the console and seeing an error there first. it might be nice to draw the user's attention to that bottom area if we have an error that's nondescript about what precisely in the configuration is problematic, kind of like if the user has not selected a boot image:

![Selection_999(341)](https://github.com/user-attachments/assets/206e07f6-050b-41f5-96fe-d654f72e9138)

i'm pretty sure if there were a rectangle drawing my eyes along to the right of the page i would have seen the error immediately, at least :) it definitely didn't help that i'd been just watching the spinner, totally ignoring anything past about the middle of the page.

**Comment by david-crespo** [comment]
Good one. It may help for us to pick a form field to attach the error too also and focus that, though that wouldn’t cover us in the case of errors we’re not specifically handling. So I agree we should make that error more in your face. One thing we can do is move it next to the buttons instead of all the way right.

**Comment by david-crespo** [comment]
Just noticed we don't focus the instance name field when we get an error that the name is taken. @benjaminleonard besides improving logic around focusing fields on errors relevant to them, what do you think about moving the footer error next to the buttons so it's harder to miss? We could even make it responsive so it's only moved next to the buttons on screens above a certain width.

**Comment by benjaminleonard** [comment]
I think next to the buttons at all sizes is probably fine. Let's see it to be sure.

**Comment by benjaminleonard** [comment]
We could also try making the errors part right aligned to a max width of `max-w-lg`. But that might overflow sooner than we'd like.
