### ISSUE TITLE
Make resource actions on detail page more discoverable

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#2419]
It occurred to me maybe this hamburger is a little too cryptic and subtle. Of course it only takes one click to know what's in there, but considering how important `start` and `stop` are to an instance (for example), they're pretty buried in the current design. 

Here's one idea (adding text to the button instead of a simple hamburger [kebab]), but really there's a whole range of possible solutions, for example pulling out dedicated start and stop buttons at top level. A hamburger is more legible as a `...rest` kind of thing than as _the_ place where these actions live.

<img width="1400" alt="image" src="https://github.com/user-attachments/assets/453bd1e3-57af-42de-b3b7-fd1c6274be52">

**Comment by benjaminleonard** [comment]
Something like this?

Still unsure as to whether we have a single button that switches between start and stop, or two. Two of course take up more space, but give further context when they are enabled/disabled. Also having a changing button will change width as it switches from Start to Stop which may or may not look funky.

Connect gives us a direct line to serial console which is a nice QoL improvement.

![Image](https://github.com/user-attachments/assets/ecbfce25-5e36-4eea-baa3-c9103074397c)

**Comment by benjaminleonard** [comment]
See alternatively:

![Image](https://github.com/user-attachments/assets/830e7a55-991c-46ae-8db8-7f7bbae8aacb)
