### ISSUE TITLE
Workshop arbitrary values help text

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#2447]
> Select an option or enter a custom value

What we have is decent, but I just want to flag that we should keep mulling it over before v11 in case we come up with something better. It might help to explain somewhere (in this help text or elsewhere) that the match works by string, and therefore it can be any string, even one that doesn't match any instances _yet_. At least, that's what I want to convey — doesn't mean we have to say it exactly like that.

https://github.com/oxidecomputer/console/blob/ce242e7764709d201576a950c0539f78439c4578/app/forms/firewall-rules-common.tsx#L124-L129

<img src="https://github.com/user-attachments/assets/c99dcdd1-102b-4a76-89e6-e5eb135ece8f" width="400" />

**Comment by charliepark** [comment]
I think if we're using the text as we currently have it in #2518 (`Use custom value: typed-in-entry`), the existing help copy we have (`Select an option or enter a custom value`) works for me.

**Comment by david-crespo** [comment]
I’m satisfied, let’s say #2518 closes this
