### ISSUE TITLE
Display group_attribute_name in IdP view

### ISSUE THREAD

**Issue by augustuswm** [oxidecomputer/console#2473]
Currently we do not display the `group_attribute_name` field from an IdP configuration in the view IdP flyout. This is a helpful value to display when debugging connection issues.

**Comment by charliepark** [comment]
Looks like this is already stubbed out; possibly just needs to be uncommented and to have the description cleaned up a little bit.
https://github.com/oxidecomputer/console/blob/a76ba5f46f2509d21c56d397e1f1cf62bd8dbbbb/app/forms/idp/edit.tsx#L107-L114

**Comment by charliepark** [comment]
How about "Name of SAML attribute with user’s comma-separated group names"?

**Comment by augustuswm** [comment]
I think we can clarify that this is the attribute being sent from the IdP. Something like "Name of the SAML attribute sent by the IdP containing a comma-separate list of groups for the authenticated user"
