### ISSUE TITLE
Instance create form: long disk names mess up table

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#2486]
Ideas:

- Wider table
- Truncate with tooltip
- Cap width of cell, forcing name to wrap

<img src="https://github.com/user-attachments/assets/706460f5-86df-4aaa-9727-928f6a87eb3b" width=480>

<img src="https://github.com/user-attachments/assets/992b68b3-de53-4779-bfcf-cfaed4024061" width=480>

**Comment by benjaminleonard** [comment]
+1 truncate with tooltip
