### ISSUE TITLE
Consolidate copy and approach to toast copy

### ISSUE THREAD

**Issue by benjaminleonard** [oxidecomputer/console#2499]
We're a little inconsistent with toast copy and CTAs at the moment. We should do a pass on consolidating them all. E.g. settling on capitalisation, use of quotes, and when to link to the resource that has been created / modified.

**Comment by david-crespo** [comment]
Agree on all points!

**Comment by charliepark** [comment]
Thoughts on

**Success**
arch-202-06-01 has been deleted

vs.

**Success**
Image deleted

?

**Comment by benjaminleonard** [comment]
I like including the resource name – it makes the action much clearer and reassures the user
