### ISSUE TITLE
Inventory page sled list should display the provision_policy value

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/console#2623]
The value of this sled property is currently not viewable in the UI. For example on rack2, 
```
oxide system hardware sled list | jq -r '.[] | .baseboard.serial + ", " + .policy.provision_policy' 
BRM42220057, provisionable
BRM44220011, provisionable
BRM42220017, provisionable
BRM42220051, provisionable
BRM44220010, provisionable
BRM42220014, provisionable
BRM42220031, provisionable
BRM42220006, provisionable
BRM27230045, non_provisionable
BRM42220009, provisionable
BRM42220016, provisionable
BRM44220005, provisionable
```
But the UI shows all of them as in service:
<img width="1306" alt="Image" src="https://github.com/user-attachments/assets/99196349-e702-4dc9-b2fc-7b79b9f86edb" />

**Comment by david-crespo** [comment]
We’re displaying `policy.kind` instead of `policy.provision_policy`.

https://github.com/oxidecomputer/console/blob/c1ebd8d9acae4ff7a09b2517265fba52ebdfe82e/app/pages/system/inventory/SledsTab.tsx#L61
