### ISSUE TITLE
Improve Table/MiniTable accessibility

### ISSUE THREAD

**Issue by zephraph** [oxidecomputer/console#762]
- Add ARIA roles
- Improve keyboard navigation
- Validate/improve screen reader experience

We should probably take some ques from https://spectrum.adobe.com/page/table/#Keyboard-interactions

**Comment by david-crespo** [comment]
I don't know what the ARIA roles would be here, it's already `<table>`, so it shouldn't need roles. Keyboard nav also seems pretty good.
