### ISSUE TITLE
Give user equivalent CLI command

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#857]
Details TBD

**Comment by charliepark** [comment]
See #2046

**Comment by david-crespo** [comment]
After talking this through with @charliepark, I think we should close this as it's not actionable enough. We do have the UI pattern now and we can use it whenever we need to. Ironically, I feel what is most useful to know about the CLI is stuff you _can't_ do on a given console page, as opposed to knowing the actual equivalent CLI command. If you're in the console looking at something, it's probably because the console is a nice way to do it. But often our forms are simplified versions of some API POST endpoint, and you might want to use the CLI to use some feature we don't expose in the console. All that is a long way of saying this issue is underspecified and we should just keep in mind in the future the possibility of using the equivalent CLI command button.
