### ISSUE TITLE
Network interfaces follow up

### ISSUE THREAD

**Issue by zephraph** [oxidecomputer/console#991]
This captures the follow up from https://github.com/oxidecomputer/console/pull/985.

- [ ] Show more details in the network interface minitable when creating custom NICs in the instance create form
- [ ] Implement the modal selection for making a NIC primary
- [ ] Address [this comment](https://github.com/oxidecomputer/console/pull/985#discussion_r909057666) if any design changes are required
- [x] #993

**Comment by david-crespo** [comment]
This is all already more or less done.
